### PR TITLE
Add code to `make.jl` so it can run as a script

### PR DESCRIPTION
**Pull request by goerz**
See https://github.com/JuliaDocs/Documenter.jl/issues/1413#issuecomment-1942392352

### CODE REVIEW

**Comment by mortenpi** [comment]
One note here: I am not sure we want to maintain the generation functionality that much here? Wouldn't we want to direct users to PkgTemplates?

**Comment by goerz** [comment]
Maybe… I was playing around with rewriting the Documenter Guide, and it would allow for a rather didactic approach where we can set up the documentation from scratch, using `@repl`/`@eval` blocks:



This would make the guide full reproducible, and `DocumenterTools.generate` would definitely help there.

**Comment by goerz** [comment]
Not quite sure yet if this really works out, though. It would be helpful if there was a `@repl` block that could also handle `pkg >` and `shell >` mode, but that would be a whole new issue to open and not completely trivial to implement.

**Comment by goerz** [comment]
Anyway, I might play around more, but I'll probably put this on the backburner until the next community call.

**Comment by goerz** [comment]
> Wouldn't we want to direct users to PkgTemplates?

Actually, you're right. `PkgTemplates` is a much better place to focus any effort on for defining best practices, and I can use that just as well in a tutorial.

**Pull request closed without merging**
