### PR TITLE
Keygen.jl

### LINKED ISSUE #5: Fix Travis.genkeys() for Windows
Refs: JuliaDocs/Documenter.jl#767 JuliaDocs/Documenter.jl#761

### LINKED ISSUE #36: ssh-keygen as a jll
Currently the package assumes access to `Sys.which` and it implies access to the `PATH` environmental variable which is not always accessible to the environment (e.g., Visual Studio Code on OSX).
The better way to implement it would be to have `ssh-keygen` as a jll.

### LINKED ISSUE #37: Keygen.jl as a separate package
Keygen.jl can be used in various situations that are not limited to Documenter. For example, many GitHub actions need tokens.

Related: https://github.com/JuliaDocs/DocumenterTools.jl/issues/36

### PR DESCRIPTION
**Pull request by aminya**
Now we have Keygen.jl: https://github.com/aminya/Keygen.jl

Merge when Keygen.jl is registered.
https://github.com/JuliaRegistries/General/pull/15941?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDkxNzI5NzgwOToxNjQxODE5Nw%3D%3D

Fixes #37 
Closes #36 here 
Removes Travis deprecation. Fixes #5 

Deprecates `genkeys` in favor of `Keygen.documenter_keygen`

### CODE REVIEW

**Comment by mortenpi** [comment]
I don't think it really makes sense to split Documenter-specific stuff into a separate package. But if Keygen would provide a neat API for calling `ssh-keygen`, returning the private and public keys, then I would be happy to depend on it.

**Comment by aminya** [comment]
The goal is to provide those APIs. In addition, the goal is to provide a single package (rather many) that people can use for generating keys for all sorts of applications. For Documenter, GitHub actions, etc. 

PkgTemplates will also use this single Keygen for generating the keys it needs for its plugins.

**Comment by mortenpi** [comment]
> The goal is to provide a single package (rather many) that people can use for generating keys for all sorts of applications (e.g Documenter, GitHub secrets, etc). So one go-to package for people, rather many spread all over the globe

I think that goal makes sense. But at this very moment it Keygen is identical to what we have here, so we'd be spreading out Documenter-related functionality. I feel that we can go in two directions here:

* DocumenterTools keeps providing `genkeys`, but would use a low-level API from Keygen to call `ssh-keygen`. Things like base64-encoding the private key etc. would still happen here. (Note: it would be perfectly fine for Keygen to also provide a high-level API to generate Documenter-compatible keys, although it would indeed duplicate the code.)

* Or, Keygen would define a clean generic API for generating SSH keys, with well-defined encoding etc. At that point we could just point Documenter docs to Keygen and just say "You need to upload Keygen-compatible keys to Travis."

Regarding the low-level API: as far as I can tell, OpenSSH_jll just provides the path to `ssh-keygen`. So the code for calling it, reading outputs and error handling is still quite a fair bit of code that would be good not to duplicate.

**Comment by aminya** [comment]
Yes, I don't expect this PR to be merged right now, but eventually, it will have the planned implementation. Once done, it will be up to you to use Keygen the way you like, but since I already asked in https://github.com/JuliaDocs/DocumenterTools.jl/issues/37, I made this PR.

**Pull request closed without merging**
