### PR TITLE
Point to DocumenterTools section in Documenter.jl's docs

### PR DESCRIPTION
**Pull request by mroavi**

### CODE REVIEW

**Comment by mroavi** [comment]
I noticed that the `docs` dir was removed from the project. Is the intention to drop DocumenterTools.jl documentation? I updated the URL to point to a working version hosted in JuliaHub.

**Comment by ViralBShah** [comment]
Seems like we should be directly pointing to the Documenter docs.

**Comment by mroavi** [comment]
Are the DocumenterTools' docstrings available there too? Personally, I found these very useful.

**Comment by ViralBShah** [comment]
Good point about the docstrings. I am not sure about that.

**Comment by fredrikekre** [comment]
> Are the DocumenterTools' docstrings available there too?

https://documenter.juliadocs.org/stable/lib/internals/documentertools/

**Comment by mroavi** [comment]
Ah perfect. Then it would be better if we update the link that there's currently in the docs to point to that url.

**Pull request merged**
